const colors = [
  {name:"Merah", hex:"#ef4444"},
  {name:"Oranye", hex:"#fb923c"},
  {name:"Kuning", hex:"#facc15"},
  {name:"Hijau", hex:"#10b981"},
  {name:"Biru", hex:"#3b82f6"},
  {name:"Indigo", hex:"#6366f1"},
  {name:"Ungu", hex:"#8b5cf6"},
  {name:"Pink", hex:"#ec4899"},
  {name:"Cyan", hex:"#06b6d4"},
  {name:"Lime", hex:"#84cc16"},
  {name:"Abu-abu", hex:"#9ca3af"},
  {name:"Hitam", hex:"#0f172a"},
  {name:"Putih", hex:"#ffffff"},
  {name:"Coklat", hex:"#8b4513"},
  {name:"Emas", hex:"#fbbf24"},
  {name:"Perak", hex:"#d1d5db"},
  {name:"Magenta", hex:"#d946ef"},
  {name:"Turquoise", hex:"#14b8a6"},
  {name:"Maroon", hex:"#7f1d1d"},
  {name:"Navy", hex:"#1e3a8a"},
  {name:"Olive", hex:"#4d7c0f"},
  {name:"Lavender", hex:"#c084fc"}
];
